services:
  django:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    container_name: turbobota_django
    command: bash -c "
        /app/wait-for-it.sh postgres:5432 -- \
        python manage.py migrate && python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    env_file:
      - .envs/.local.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:16.2
    container_name: turbodota_postgres
    env_file:
      - .envs/.local.env
    ports:
      - "5432"

  redis:
    image: "redis:6.2-alpine"
    container_name: turbodota_redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    container_name: turbodota_celery
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    command: celery -A config worker -l info --concurrency=1
    depends_on:
      - redis
      - postgres

  celery-beat:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    container_name: turbodota_celerybeat
    environment:  
      - DJANGO_SETTINGS_MODULE=config.settings.local
    command: celery -A config beat -l info
    depends_on:
      - redis
      - postgres
