services:
  db:
    image: postgres:16.2
    restart: always
    container_name: postgres-local
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432"

  web:
    build: .
    container_name: web-local
    command: bash -c "
        /code/wait-for-it.sh db:5432 -- \
        python manage.py migrate && python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - STEAM_API_KEY=${STEAM_API_KEY}
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .:/code
    depends_on:
      - db

  redis:
    image: "redis:6.2-alpine"
    container_name: redis-local
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery-local
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    command: celery -A config worker -l info
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    container_name: celery-beat-local
    environment:  
      - DJANGO_SETTINGS_MODULE=config.settings.dev
    command: celery -A config beat -l info
    depends_on:
      - redis
      - db
