[project]
name = "dota2-turbo"
version = "1.0"
description = "turbodota.xyz 2.0 version"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==5.2.7",
    "python-decouple>=3.8",
    "social-auth-app-django>=5.6.0",
]
